doc: i386 fix
src/sfptpd_statistics.c: In function ‘stats_range_history_write_data’:
src/sfptpd_statistics.c:518:62: error: passing argument 4 of ‘sfptpd_local_strftime’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  518 |                                               "%Y-%m-%d %X", &entry->min_time.sec);
      |                                                              ^~~~~~~~~~~~~~~~~~~~
      |                                                              |
      |                                                              int64_t * {aka long long int *}
In file included from src/include/sfptpd_logging.h:16,
                 from src/sfptpd_statistics.c:20:
src/include/sfptpd_misc.h:144:83: note: expected ‘const time_t *’ {aka ‘const long int *’} but argument is of type ‘int64_t *’ {aka ‘long long int *’}
  144 | void sfptpd_local_strftime(char *s, size_t max, const char *format, const time_t *timep);
      |                                                                     ~~~~~~~~~~~~~~^~~~~

->

UNIT TEST RESULTS SUMMARY
seed: 1715450424

|    | Unit test   | Run     | Result                    |
| -- | ----------- | ------- | ------------------------- |
|  0 | config      | Run     | Pass                      |
|  1 | hash        | Run     | Pass                      |
|  2 | stats       | Run     | Pass                      |
|  3 | filters     | Not run |                           |
|  4 | threading   | Not run |                           |
|  5 | bic         | Run     | Pass                      |
|  6 | fmds        | Not run |                           |
|  7 | link        | Run     | Pass                      |
|  8 | time        | Run     | Pass                      |

Linux cook 6.5.0-3-686 #1 SMP PREEMPT_DYNAMIC Debian 6.5.8-1 (2023-10-22) i686 GNU/Linux

2024-02-01 09:40:33.999310: info: Solarflare Enhanced PTP Daemon, version 3.8.0.1000
2024-02-01 09:40:34.001436: debug: config: entering section 'general'
2024-02-01 09:40:34.001564: debug: config: created freerun instance 'fr1'
2024-02-01 09:40:34.001620: debug: config [general]: sync_module = freerun fr1
2024-02-01 09:40:34.001682: debug: config [general]: message_log = syslog
2024-02-01 09:40:34.001746: debug: config [general]: stats_log = off
2024-02-01 09:40:34.001812: debug: config [general]: clock_readonly = system
2024-02-01 09:40:34.001875: debug: config [general]: non_solarflare_nics = off
2024-02-01 09:40:34.001971: debug: config: created crny implicit instance crny0
2024-02-01 09:40:34.002031: debug: config: entering section 'fr1'
2024-02-01 09:40:34.002090: debug: config [fr1]: interface = system
2024-02-01 09:40:34.045423: debug: link: interface additions (+), deletions (-) and changes (<--, -->):
2024-02-01 09:40:34.045549: debug: | if_index | if_name          | flags | kind     | mode | role  | link   | master | active | vlan  | phc | permaddr          |
2024-02-01 09:40:34.045613: debug: |        1 + lo               | 10049 |          |      |       |      0 |      0 |      0 |     0 |  -1 |                   |
2024-02-01 09:40:34.045669: debug: |        2 + enp3s0           | 01003 |          |      |       |      0 |      0 |      0 |     0 |  -1 | 00:13:77:f9:d3:01 |
2024-02-01 09:40:34.045724: debug: |        3 + wlp2s0           | 11043 |          |      |       |      0 |      0 |      0 |     0 |  -1 | 00:24:2c:4c:eb:48 |
2024-02-01 09:40:34.045778: debug: |        4 + docker0          | 01003 | bridge   |      |       |      0 |      0 |      0 |     0 |  -1 |                   |
2024-02-01 09:40:34.046035: notice: clock system won't ever be stepped or slewed due to clock-readonly configuration
2024-02-01 09:40:34.046185: info: no clock frequency correction file /var/lib/sfptpd/freq-correction-system
2024-02-01 09:40:34.046255: debug: clock system: no saved freq adj available
2024-02-01 09:40:34.046613: debug: interface lo: is virtual - ignoring
2024-02-01 09:40:34.047732: debug: interface enp3s0: hw 00:13:77:f9:d3:01, flags
2024-02-01 09:40:34.047831: debug: interface enp3s0: device 11ab:4354 at 0000:03:00.0
2024-02-01 09:40:34.049359: debug: interface wlp2s0: is wireless - ignoring
2024-02-01 09:40:34.049483: debug: interface docker0: is a bridge - ignoring
2024-02-01 09:40:34.049542: debug: dump of table interfaces, 1 search keys, 1 sort keys
2024-02-01 09:40:34.049622: debug: | if_index |   name |               mac | clock | nic | deleted | ptp | type | bus_addr_nic |
2024-02-01 09:40:34.049674: debug: |----------+--------+-------------------+-------+-----+---------+-----+------+--------------|
2024-02-01 09:40:34.049737: debug: |        2 | enp3s0 | 00:13:77:f9:d3:01 |    -1 |  -1 |         |     | phys |   0000:03:00 |
2024-02-01 09:40:34.049785: debug: requested clocks list:-
2024-02-01 09:40:34.049832: debug:   | type    | nic_id | clk    | phc diff method    | short name | long name
2024-02-01 09:40:34.049878: debug:   +---------+--------+--------+--------------------+------------+----------
2024-02-01 09:40:34.049921: debug:   | sys     |                                      | system     | system [read-only]
2024-02-01 09:40:34.050081: debug: retained capabilities cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_time=ep
2024-02-01 09:40:34.069199: debug: clocks: poll interval to 0.062500000000s
2024-02-01 09:40:34.069499: debug: sync module 1, instances 1
2024-02-01 09:40:34.069601: info: freerun: creating sync-module
2024-02-01 09:40:34.069659: info: freerun fr1: creating sync-instance
2024-02-01 09:40:34.070596: debug: created sync module freerun
2024-02-01 09:40:34.070708: debug: created sync instance fr1
2024-02-01 09:40:34.070768: debug: sync module 4, instances 0
2024-02-01 09:40:35.147308: info: ntp: sfptpd is configured to not discipline the system clock, ntpd may do so
2024-02-01 09:40:35.147465: info: ntp: currently in state ntp-slave
2024-02-01 09:40:35.147813: debug: created sync module ntp
2024-02-01 09:40:35.148186: debug: sync module 5, instances 1
2024-02-01 09:40:35.148304: debug: crny: creating sync-module
2024-02-01 09:40:35.240150: debug: created sync module crny
2024-02-01 09:40:35.241077: debug: created sync instance crny0
2024-02-01 09:40:35.241149: debug: maximum servos required 17 (including 16 spare for hotplugging)
2024-02-01 09:40:35.242542: info: selection: rank 1: fr1 by rule state (2) <- BEST
2024-02-01 09:40:35.242642: info: selection: rank 2: crny0 <- WORST
2024-02-01 09:40:35.242828: debug: new grandmaster info: instance = fr1, id = 0000:0000:0000:0000, remote = no, clock class = freerunning, time source = internal oscillator, accuracy = inf, steps removed = 0
2024-02-01 09:40:35.243075: debug: total servos 17, active servos 0, lrc system
2024-02-01 09:40:35.245384: info: selected sync instance fr1 ([none] was active for 0.000s)
2024-02-01 09:40:35.246050: debug: sync engine created successfully
2024-02-01 09:40:35.246116: debug: main: sending RUN message to engine
2024-02-01 09:40:35.246567: debug: engine: sending RUN message to sync module type 1
2024-02-01 09:40:35.247969: debug: engine: sending RUN message to sync module type 4
2024-02-01 09:40:35.248280: debug: engine: sending RUN message to sync module type 5
2024-02-01 09:41:00.515134: notice: received exit signal
2024-02-01 09:41:00.528259: debug: clocks: shutting down